import type { Usuario, Sala, Aula, Chamado } from "./types"

export const usuarios: Partial<Usuario>[] = [
  {
    id: "1",
    nome: "Prof. João Silva",
    email: "joao.silva@universidade.edu",
    tipo: "professor",
  },
  {
    id: "2",
    nome: "Maria Santos",
    email: "maria.santos@universidade.edu",
    tipo: "coordenador",
  },
  {
    id: "3",
    nome: "Prof. Ana Costa",
    email: "ana.costa@universidade.edu",
    tipo: "professor",
  },
  {
    id: "4",
    nome: "Carlos Oliveira",
    email: "carlos.oliveira@universidade.edu",
    tipo: "suporte",
  },
  {
    id: "5",
    nome: "Fernanda Lima",
    email: "fernanda.lima@universidade.edu",
    tipo: "suporte",
  },
]

export const salas: Sala[] = [
  {
    id: "1",
    nome: "Sala 101",
    capacidade: 40,
    equipamentos: ["Projetor", "Computador", "Quadro Branco", "Ar Condicionado"],
    status: "disponivel",
    localizacao: "Bloco A - 1º Andar",
  },
  {
    id: "2",
    nome: "Sala 102",
    capacidade: 30,
    equipamentos: ["Projetor", "Quadro Branco"],
    status: "ocupada",
    localizacao: "Bloco A - 1º Andar",
  },
  {
    id: "3",
    nome: "Lab Informática",
    capacidade: 25,
    equipamentos: ["20 Computadores", "Projetor", "Ar Condicionado"],
    status: "disponivel",
    localizacao: "Bloco B - 2º Andar",
  },
  {
    id: "4",
    nome: "Auditório",
    capacidade: 100,
    equipamentos: ["Sistema de Som", "Projetor", "Microfone", "Ar Condicionado"],
    status: "manutencao",
    localizacao: "Bloco C - Térreo",
  },
]

export const aulas: Aula[] = [
  {
    id: "1",
    disciplina: "Programação Web",
    professor: "Prof. João Silva",
    professorId: "1",
    salaId: "1",
    sala: "Sala 101",
    dataHora: "2024-12-02T08:00:00" as any,
    duracao: 120,
    status: "agendada",
  },
  {
    id: "2",
    disciplina: "Banco de Dados",
    professor: "Prof. Ana Costa",
    professorId: "3",
    salaId: "3",
    sala: "Lab Informática",
    dataHora: "2024-12-02T10:00:00" as any,
    duracao: 90,
    status: "agendada",
  },
  {
    id: "3",
    disciplina: "Algoritmos",
    professor: "Prof. João Silva",
    professorId: "1",
    salaId: "2",
    sala: "Sala 102",
    dataHora: "2024-12-02T14:00:00" as any,
    duracao: 120,
    status: "em_andamento",
  },
]

export const chamados: Chamado[] = [
  {
    id: "1",
    titulo: "Projetor não funciona",
    descricao: "O projetor da sala 101 não está ligando",
    tipo: "equipamento",
    prioridade: "alta",
    status: "em_andamento",
    salaId: "1",
    sala: "Sala 101",
    solicitante: "Prof. João Silva",
    solicitanteId: "1",
    dataAbertura: "2024-12-01T09:00:00" as any,
    responsavelId: "4",
    responsavel: "Carlos Oliveira",
  },
  {
    id: "2",
    titulo: "Ar condicionado com problema",
    descricao: "Ar condicionado fazendo muito barulho",
    tipo: "manutencao",
    prioridade: "media",
    status: "em_andamento",
    salaId: "4",
    sala: "Auditório",
    solicitante: "Maria Santos",
    solicitanteId: "2",
    dataAbertura: "2024-11-30T15:30:00" as any,
    responsavelId: "5",
    responsavel: "Fernanda Lima",
  },
  {
    id: "3",
    titulo: "Falta de canetões",
    descricao: "Quadro branco sem canetões para uso",
    tipo: "equipamento",
    prioridade: "baixa",
    status: "resolvido",
    salaId: "2",
    sala: "Sala 102",
    solicitante: "Prof. Ana Costa",
    solicitanteId: "3",
    dataAbertura: "2024-11-29T11:00:00" as any,
    dataResolucao: "2024-11-30T08:00:00" as any,
    responsavelId: "4",
    responsavel: "Carlos Oliveira",
  },
  {
    id: "4",
    titulo: "Computador não liga",
    descricao: "Computador da mesa do professor não está funcionando",
    tipo: "equipamento",
    prioridade: "alta",
    status: "aberto",
    salaId: "1",
    sala: "Sala 101",
    solicitante: "Prof. João Silva",
    solicitanteId: "1",
    dataAbertura: "2024-12-02T08:30:00" as any,
  },
]
