import type { Usuario, Sala, Aula, Chamado } from "./types"

export const usuarios: Usuario[] = [
  {
    id: "1",
    nome: "Prof. João Silva",
    email: "joao.silva@universidade.edu",
    tipo: "professor",
    ativo: true,
    dataCriacao: "2024-01-15T10:00:00",
    ultimoAcesso: "2024-12-01T08:30:00",
    departamento: "Ciência da Computação",
    telefone: "(11) 98765-4321",
    foto: "/placeholder.svg?height=128&width=128",
  },
  {
    id: "2",
    nome: "Maria Santos",
    email: "maria.santos@universidade.edu",
    tipo: "coordenador",
    ativo: true,
    dataCriacao: "2023-11-10T09:00:00",
    ultimoAcesso: "2024-12-02T09:15:00",
    departamento: "Administração Acadêmica",
    telefone: "(11) 91234-5678",
    foto: "/placeholder.svg?height=128&width=128",
  },
  {
    id: "3",
    nome: "Prof. Ana Costa",
    email: "ana.costa@universidade.edu",
    tipo: "professor",
    ativo: true,
    dataCriacao: "2024-02-20T14:30:00",
    ultimoAcesso: "2024-12-01T13:45:00",
    departamento: "Engenharia de Software",
    telefone: "(11) 97654-3210",
    foto: "/placeholder.svg?height=128&width=128",
  },
  {
    id: "4",
    nome: "Carlos Oliveira",
    email: "carlos.oliveira@universidade.edu",
    tipo: "suporte",
    ativo: true,
    dataCriacao: "2024-03-05T11:20:00",
    ultimoAcesso: "2024-12-02T08:00:00",
    departamento: "Suporte Técnico",
    telefone: "(11) 95555-9999",
    foto: "/placeholder.svg?height=128&width=128",
  },
  {
    id: "5",
    nome: "Fernanda Lima",
    email: "fernanda.lima@universidade.edu",
    tipo: "suporte",
    ativo: true,
    dataCriacao: "2024-03-10T09:45:00",
    ultimoAcesso: "2024-12-01T16:30:00",
    departamento: "Suporte Técnico",
    telefone: "(11) 94444-8888",
    foto: "/placeholder.svg?height=128&width=128",
  },
  {
    id: "6",
    nome: "Roberto Almeida",
    email: "roberto.almeida@universidade.edu",
    tipo: "professor",
    ativo: false,
    dataCriacao: "2023-10-15T10:30:00",
    ultimoAcesso: "2024-06-15T14:20:00",
    departamento: "Matemática",
    telefone: "(11) 93333-7777",
    foto: "/placeholder.svg?height=128&width=128",
  },
  {
    id: "7",
    nome: "Luciana Ferreira",
    email: "luciana.ferreira@universidade.edu",
    tipo: "professor",
    ativo: true,
    dataCriacao: "2024-04-12T08:15:00",
    ultimoAcesso: "2024-12-01T10:45:00",
    departamento: "Física",
    telefone: "(11) 92222-6666",
    foto: "/placeholder.svg?height=128&width=128",
  },
]

export const salas: Sala[] = [
  {
    id: "1",
    nome: "Sala 101",
    capacidade: 40,
    equipamentos: ["Projetor", "Computador", "Quadro Branco", "Ar Condicionado"],
    statusManual: "disponivel",
    localizacao: "Bloco A - 1º Andar",
  },
  {
    id: "2",
    nome: "Sala 102",
    capacidade: 30,
    equipamentos: ["Projetor", "Quadro Branco"],
    statusManual: "disponivel",
    localizacao: "Bloco A - 1º Andar",
  },
  {
    id: "3",
    nome: "Lab Informática",
    capacidade: 25,
    equipamentos: ["20 Computadores", "Projetor", "Ar Condicionado"],
    statusManual: "disponivel",
    localizacao: "Bloco B - 2º Andar",
  },
  {
    id: "4",
    nome: "Auditório",
    capacidade: 100,
    equipamentos: ["Sistema de Som", "Projetor", "Microfone", "Ar Condicionado"],
    statusManual: "manutencao",
    localizacao: "Bloco C - Térreo",
  },
]

export const aulas: Aula[] = [
  {
    id: "1",
    disciplina: "Programação Web",
    professores: [
      { id: "1", nome: "Prof. João Silva" },
      { id: "3", nome: "Prof. Ana Costa" },
    ],
    salaId: "1",
    sala: "Sala 101",
    salasAtribuicoes: [
      { professorId: "1", professorNome: "Prof. João Silva", salaId: "1", salaNome: "Sala 101" },
      { professorId: "3", professorNome: "Prof. Ana Costa", salaId: "2", salaNome: "Sala 102" },
    ],
    horarios: [
      { diaSemana: 1, horaInicio: "08:00", horaFim: "10:00" }, // Segunda
      { diaSemana: 3, horaInicio: "08:00", horaFim: "10:00" }, // Quarta
    ],
    status: "agendada",
    cor: "#3b82f6",
    dataInicioAnoLetivo: "2024-08-05",
    dataFimAnoLetivo: "2024-12-15",
  },
  {
    id: "2",
    disciplina: "Banco de Dados",
    professores: [{ id: "3", nome: "Prof. Ana Costa" }],
    salaId: "3",
    sala: "Lab Informática",
    salasAtribuicoes: [
      { professorId: "3", professorNome: "Prof. Ana Costa", salaId: "3", salaNome: "Lab Informática" },
    ],
    horarios: [
      { diaSemana: 2, horaInicio: "10:00", horaFim: "11:30" }, // Terça
      { diaSemana: 4, horaInicio: "10:00", horaFim: "11:30" }, // Quinta
    ],
    status: "agendada",
    cor: "#10b981",
    dataInicioAnoLetivo: "2024-08-05",
    dataFimAnoLetivo: "2024-12-15",
  },
  {
    id: "3",
    disciplina: "Algoritmos",
    professores: [{ id: "1", nome: "Prof. João Silva" }],
    salaId: "2",
    sala: "Sala 102",
    salasAtribuicoes: [{ professorId: "1", professorNome: "Prof. João Silva", salaId: "2", salaNome: "Sala 102" }],
    horarios: [
      { diaSemana: 1, horaInicio: "14:00", horaFim: "16:00" }, // Segunda
      { diaSemana: 5, horaInicio: "14:00", horaFim: "16:00" }, // Sexta
    ],
    status: "agendada",
    cor: "#f59e0b",
    dataInicioAnoLetivo: "2025-02-10",
    dataFimAnoLetivo: "2025-06-30",
  },
  {
    id: "4",
    disciplina: "Estrutura de Dados",
    professores: [
      { id: "3", nome: "Prof. Ana Costa" },
      { id: "7", nome: "Luciana Ferreira" },
    ],
    salaId: "1",
    sala: "Sala 101",
    salasAtribuicoes: [
      { professorId: "3", professorNome: "Prof. Ana Costa", salaId: "1", salaNome: "Sala 101" },
      { professorId: "7", professorNome: "Luciana Ferreira", salaId: "3", salaNome: "Lab Informática" },
    ],
    horarios: [
      { diaSemana: 2, horaInicio: "19:00", horaFim: "21:00" }, // Terça
      { diaSemana: 4, horaInicio: "19:00", horaFim: "21:00" }, // Quinta
    ],
    status: "agendada",
    cor: "#8b5cf6",
    dataInicioAnoLetivo: "2024-08-05",
    dataFimAnoLetivo: "2024-12-15",
  },
  {
    id: "5",
    disciplina: "Física Aplicada",
    professores: [{ id: "7", nome: "Luciana Ferreira" }],
    salaId: "2",
    sala: "Sala 102",
    salasAtribuicoes: [{ professorId: "7", professorNome: "Luciana Ferreira", salaId: "2", salaNome: "Sala 102" }],
    horarios: [{ diaSemana: 3, horaInicio: "14:00", horaFim: "16:00" }],
    status: "agendada",
    cor: "#ec4899",
    dataInicioAnoLetivo: "2025-02-10",
    dataFimAnoLetivo: "2025-06-30",
  },
  {
    id: "6",
    disciplina: "Redes de Computadores",
    professores: [{ id: "1", nome: "Prof. João Silva" }],
    salaId: "3",
    sala: "Lab Informática",
    salasAtribuicoes: [
      { professorId: "1", professorNome: "Prof. João Silva", salaId: "3", salaNome: "Lab Informática" },
    ],
    horarios: [{ diaSemana: 1, horaInicio: "19:00", horaFim: "22:00" }],
    status: "agendada",
    cor: "#06b6d4",
    dataInicioAnoLetivo: "2024-08-05",
    dataFimAnoLetivo: "2024-12-15",
  },
  {
    id: "7",
    disciplina: "Inteligência Artificial",
    professores: [{ id: "3", nome: "Prof. Ana Costa" }],
    salaId: "1",
    sala: "Sala 101",
    salasAtribuicoes: [{ professorId: "3", professorNome: "Prof. Ana Costa", salaId: "1", salaNome: "Sala 101" }],
    horarios: [{ diaSemana: 5, horaInicio: "08:00", horaFim: "10:00" }],
    status: "agendada",
    cor: "#f97316",
    dataInicioAnoLetivo: "2024-08-05",
    dataFimAnoLetivo: "2024-12-15",
  },
  {
    id: "8",
    disciplina: "Cálculo I - Turma A",
    professores: [{ id: "7", nome: "Luciana Ferreira" }],
    salaId: "1",
    sala: "Sala 101",
    salasAtribuicoes: [{ professorId: "7", professorNome: "Luciana Ferreira", salaId: "1", salaNome: "Sala 101" }],
    horarios: [{ diaSemana: 2, horaInicio: "08:00", horaFim: "10:00" }],
    status: "agendada",
    cor: "#14b8a6",
    dataInicioAnoLetivo: "2025-02-10",
    dataFimAnoLetivo: "2025-06-30",
  },
  {
    id: "9",
    disciplina: "Cálculo I - Turma B",
    professores: [{ id: "1", nome: "Prof. João Silva" }],
    salaId: "2",
    sala: "Sala 102",
    salasAtribuicoes: [{ professorId: "1", professorNome: "Prof. João Silva", salaId: "2", salaNome: "Sala 102" }],
    horarios: [{ diaSemana: 2, horaInicio: "08:00", horaFim: "10:00" }],
    status: "agendada",
    cor: "#14b8a6",
    dataInicioAnoLetivo: "2025-02-10",
    dataFimAnoLetivo: "2025-06-30",
  },
]

export const chamados: Chamado[] = [
  {
    id: "1",
    titulo: "Projetor não funciona",
    descricao: "O projetor da sala 101 não está ligando",
    tipo: "equipamento",
    prioridade: "alta",
    status: "em_andamento",
    salaId: "1",
    sala: "Sala 101",
    solicitante: "Prof. João Silva",
    solicitanteId: "1",
    dataAbertura: "2024-12-01T09:00:00",
    responsavelId: "4",
    responsavel: "Carlos Oliveira",
  },
  {
    id: "2",
    titulo: "Ar condicionado com problema",
    descricao: "Ar condicionado fazendo muito barulho",
    tipo: "manutencao",
    prioridade: "media",
    status: "em_andamento",
    salaId: "4",
    sala: "Auditório",
    solicitante: "Maria Santos",
    solicitanteId: "2",
    dataAbertura: "2024-11-30T15:30:00",
    responsavelId: "5",
    responsavel: "Fernanda Lima",
  },
  {
    id: "3",
    titulo: "Falta de canetões",
    descricao: "Quadro branco sem canetões para uso",
    tipo: "equipamento",
    prioridade: "baixa",
    status: "resolvido",
    salaId: "2",
    sala: "Sala 102",
    solicitante: "Prof. Ana Costa",
    solicitanteId: "3",
    dataAbertura: "2024-11-29T11:00:00",
    dataResolucao: "2024-11-30T08:00:00",
    responsavelId: "4",
    responsavel: "Carlos Oliveira",
  },
  {
    id: "4",
    titulo: "Computador não liga",
    descricao: "Computador da mesa do professor não está funcionando",
    tipo: "equipamento",
    prioridade: "alta",
    status: "aberto",
    salaId: "1",
    sala: "Sala 101",
    solicitante: "Prof. João Silva",
    solicitanteId: "1",
    dataAbertura: "2024-12-02T08:30:00",
  },
]
